# Generated by Django 4.0.4 on 2022-05-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac', '0003_alter_vaccineshot_shot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineshot',
            name='shot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
