# Generated by Django 4.0.4 on 2022-05-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac', '0005_alter_vaccineshot_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineshot',
            name='city',
            field=models.CharField(choices=[], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccineshot',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
