# Generated by Django 4.0.4 on 2022-05-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac', '0006_vaccineshot_city_alter_vaccineshot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineshot',
            name='city',
            field=models.CharField(choices=[], max_length=255),
        ),
    ]
